language: java
jdk:
- oraclejdk8
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-fd 3 3<tmp.txt secret.gpg.gpg
script: mvn verify -Prelease -Dhp.iod.apiKey=$API_KEY -Dhp.dev.iod.apiKey=$DEV_API_KEY
after_success: bash travis.sh
env:
  global:
  # SONATYPE_USERNAME
  - secure: jq/0tVqf831RPulhfJLAtgnJOmW9ghTbvReLlXeEyzmoOkynh8ZeCrYJx2MsPVccUo+DX0drZMWrE0ubfkq3FQ61yOwQrivNcpMYrc2lti28fD37uop1ZEGfBkwI2nH18Oj2LKc2oPlst2/cBd/3++prgUY0NR6mip4Oou4zlek=
  # SONATYPE_PASSWORD
  - secure: YaK4dgirO1Aml2AwPEJ0w4H1FkZISgxzYo5Tm24xc8gYFeaeA4eyEgPTWW9Ced3DeEKjFL3HeJeynuzMVLCWazTnF4F0OJLSJxXkEU+BkwsIg8J9fe2bj6/PVUvsMubUFh1QXl+F2c5y9dgIC358YV19P5JwqO1jjEi11dyEbck=
  # GPG_PASSPHRASE
  - secure: GCvrxnYMoFFahKO4rJ9sQV1w347iLGhmpk+kNF4fC+CX/D0/aXSOX4EYwAV7/EEWmgAumVhRdbpJqLVSBMMP3pDKz0ECtw7M0GdmWjlFpmfVISS23sOPulin9CCOGIDdInZDYU5Saw03rPyO/3YsyVshucL216fkJ/3pUaCAIs0=
  # GPG_KEYID
  - secure: QcG6fFkclBcM/qxTy3/PA3yAqgVn7vjev8i330N+aivKLqeLSmLJ+nmc9HkQ+F/R4RkJUaeJVSPI05yZgY3nDGl+v1jVLAUINf7TSeqsQvIqRzrVS+xl9f2lX4FyFGOe/GMzpBBM5oM0WC0iP8VHalKjjrg2YFD42rTSaHA3cy8=
  # GPG_KEY
  - secure: U1ZsCQWw+SgvOlJZxvmKBajNzJ6TPmB7GVQD/Q5X2baVH/KY4R0b+jjZz+y3I0dAEwFCWEwNJ9kZdVShqlwkyQskK5NlRRR44fgB8pt6g9o5CepeuKVIRjoxYSD3u8gaRkwXt0gKPlRGSnS35pzWkSA7sanDsrv5C50KJGlV2Ls=
  # API_KEY
  - secure: XD7/u+zC3hO4Nj9fMjg6YrIBFxcqrbkOGpK96NKy2op9Pkc3R/OaDQAI33mD27yMkdNgspL4Cu8xmEy8496yxWkPPLMfeEJJoC64wRkALN9nbwhMssQh/f1fe7oL71bsdwt0Da9k+Wlsokx6thXmYOtdWS5SKd+ISC7PzhiEIKY=
  # DEV_API_KEY
  - secure: BTkzfC47geKHM/e0xSTPVzmR/Zgjke288lrPVHyyv3hb61Vilzp0WGA8kDlc47kdUyPBzVfvVCRa/zr0ba2VaTnhn8jn8ApPz6cpngWJumnPjky5vfRV/XYx+8QtiVj8ED6csuACa/LPbbzLHnkAMLUe42yRUnL3pJbfrJf3uuM=
  # GITHUB_TOKEN
  - secure: jciupo3CbAcfu4Ml8ULHQtD2ih1c74e1eA8iAi9wRl0CQGR3a6pgB2rhmrRore5QOUoPOLc5kjRpamPG7G7u7EsqRKNfDRZ4RpCPkExMsLQcgi1Ayh4uxPF2t0/7i+LaRgjsG6cOjsFnHQWTC6UzXYaemCUEWKB65Uki8l7ky9w=
